### ISSUE TITLE
Where is the folder shortcut after click on the executable file?

### ISSUE THREAD

**Issue by chen1247** [licitdev/im4717-macos#1]
Hi, thanks for your guide oon EE/IM4717 guide on macos.

I wonder during the folder mapping, after clicking on the exe file, where the folder shortcut will be shown?

**Comment by licitdev** [comment]
The folder shortcut will be shown in the same folder as the executable `.sh` file. 
An empty folder should be created even if the virtual machine is not started.

**Comment by chen1247** [comment]
hi, I cannot find the shortcut under the same folder as the executable file.

Attach the executable file as below:

#TODO: Update the 'x' in user based on the second number of tutorial group.
#Example, if your tutorial group is F311, then your user should be f31ee.
user="f34ee"

#DO NOT CHANGE ANYTHING BELOW UNLESS YOU KNOW WHAT YOU ARE DOING
folder="$user-shortcut"
cwd="`dirname \"$0\"`" 
if [ -d "$cwd/$folder" ]
then
	umount  $cwd/$folder
	rm -r $cwd/$folder
else
	mkdir $cwd/$folder
	mount_smbfs //$user:$user@192.168.56.2/$user $cwd/$folder
fi
osascript -e 'tell application "Terminal" to quit' &
exit

**Comment by chen1247** [comment]
and I comfirm that my virtual machine is on~ Thanks

**Comment by licitdev** [comment]
Please join my zoom call [here](https://us04web.zoom.us/j/73885542306?pwd=MWMvSXF5MVhFK05xOHQ2dE9ZQmExdz09).

**Comment by licitdev** [comment]
Please move your executable file to the desktop or another folder outside the virtual iCloud folder. Cheers!

**Comment by chen1247** [comment]
Thanks a lot!!!!!!
